### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by ale-trevizoli** [supremainc/sfm-unifingerui#1]
Hi. I cannot found Source Code for UNIGUI...could you publish it? Because have source code link, but inside only compiled exe file.

**Comment by hyeonchang** [comment]
Sorry, we are preparing to release. Currently, we provide the C/C++ SDK (including UnifingerUI) only for our customer. Please send an inquiry about the SDK to the sales division (sfmsales@suprema.co.kr)
Thanks.
